version: '3.8'

volumes:
  sessions_vol:

services:
  adk_frontend:
    build:
      context: ./adk_frontend
      dockerfile: Dockerfile
    volumes:
      - sessions_vol:/app/sessions.db  # Sync the DB file
    ports:
      - "80:3000"
    container_name: adk_frontend
    networks:
      - adk_network

  adk_backend:
    build:
      context: ./adk_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: adk_backend
    networks:
      - adk_network

networks:
  adk_network:
    driver: bridge 